### ISSUE TITLE
Indentation Issue

### ISSUE THREAD

**Issue by Tapispisan-YvesJohn** [PUP-BSIT/ex7-digital_dynasty#1]
https://github.com/PUP-BSIT/ex7-digital_dynasty/blob/c9d47da24700cd6b08706e82bd71c8592a812a95/Reyes_JohnRuiz/Reyes_JohnRuiz.html#L1C4-L2C11

https://github.com/PUP-BSIT/ex7-digital_dynasty/blob/c9d47da24700cd6b08706e82bd71c8592a812a95/Reyes_JohnRuiz/Reyes_JohnRuiz.html#L85C1-L86C12
Use proper indentation for better reading of the code. These are some of the indentation to be fixed for @REYESJOHNRUIZ.

**Comment by Tapispisan-YvesJohn** [comment]
Same issue: 
https://github.com/PUP-BSIT/ex7-digital_dynasty/blob/c9d47da24700cd6b08706e82bd71c8592a812a95/Reyes_JohnRuiz/works/InformationTechnology.html#L45C1-L46C15

https://github.com/PUP-BSIT/ex7-digital_dynasty/blob/c9d47da24700cd6b08706e82bd71c8592a812a95/Reyes_JohnRuiz/works/Business.html#L36C1-L37C15

https://github.com/PUP-BSIT/ex7-digital_dynasty/blob/c9d47da24700cd6b08706e82bd71c8592a812a95/Reyes_JohnRuiz/works/CoastGuard.html#L35C1-L36C15

https://github.com/PUP-BSIT/ex7-digital_dynasty/blob/c9d47da24700cd6b08706e82bd71c8592a812a95/Reyes_JohnRuiz/works/Marketing.html#L42C1-L43C15

**Comment by Villa-VillaDiana** [comment]
Same issue with @Reyes-PaulAngelo 
https://github.com/PUP-BSIT/ex7-digital_dynasty/blob/c9d47da24700cd6b08706e82bd71c8592a812a95/Reyes_PaulAngelo/Reyes_Paul-Angelo.html#L3-L10
https://github.com/PUP-BSIT/ex7-digital_dynasty/blob/c9d47da24700cd6b08706e82bd71c8592a812a95/Reyes_PaulAngelo/Reyes_Paul-Angelo.html#L11-L104
https://github.com/PUP-BSIT/ex7-digital_dynasty/blob/c9d47da24700cd6b08706e82bd71c8592a812a95/Reyes_PaulAngelo/works/Broadcasting.html#L3-L8
https://github.com/PUP-BSIT/ex7-digital_dynasty/blob/c9d47da24700cd6b08706e82bd71c8592a812a95/Reyes_PaulAngelo/works/Broadcasting.html#L9-L42
https://github.com/PUP-BSIT/ex7-digital_dynasty/blob/c9d47da24700cd6b08706e82bd71c8592a812a95/Reyes_PaulAngelo/works/IT.html#L3-L8
https://github.com/PUP-BSIT/ex7-digital_dynasty/blob/c9d47da24700cd6b08706e82bd71c8592a812a95/Reyes_PaulAngelo/works/IT.html#L9-L47
https://github.com/PUP-BSIT/ex7-digital_dynasty/blob/c9d47da24700cd6b08706e82bd71c8592a812a95/Reyes_PaulAngelo/works/IT.html#L46
https://github.com/PUP-BSIT/ex7-digital_dynasty/blob/c9d47da24700cd6b08706e82bd71c8592a812a95/Reyes_PaulAngelo/works/Laws.html#L3-L8
https://github.com/PUP-BSIT/ex7-digital_dynasty/blob/c9d47da24700cd6b08706e82bd71c8592a812a95/Reyes_PaulAngelo/works/Laws.html#L9-L42
https://github.com/PUP-BSIT/ex7-digital_dynasty/blob/c9d47da24700cd6b08706e82bd71c8592a812a95/Reyes_PaulAngelo/works/Medicine.html#L3-L8
https://github.com/PUP-BSIT/ex7-digital_dynasty/blob/c9d47da24700cd6b08706e82bd71c8592a812a95/Reyes_PaulAngelo/works/Medicine.html#L9-L41
https://github.com/PUP-BSIT/ex7-digital_dynasty/blob/c9d47da24700cd6b08706e82bd71c8592a812a95/Reyes_PaulAngelo/works/Teachers.html#L3-L8
https://github.com/PUP-BSIT/ex7-digital_dynasty/blob/c9d47da24700cd6b08706e82bd71c8592a812a95/Reyes_PaulAngelo/works/Teachers.html#L9-L42

**Comment by bergado-shamma** [comment]
Thank you po 💙

**Comment by norona-marynicole** [comment]
Thank you po!
