### ISSUE TITLE
Excess Spacing

### ISSUE THREAD

**Issue by Tapispisan-YvesJohn** [PUP-BSIT/ex7-digital_dynasty#10]
Reyes_JohnRuiz/style.css

Check for excess spaces.  For example:
.container {
    max-width: 1200px;
    margin: 0 auto;
    padding: 20px;
    display: flex;
    flex-direction: column;
    align-items: flex-start;    
    background-color: rgba(128, 128, 128, 0.8); 
}

(this can be remove for better readability)
.header {
    background-color: transparent;
    color: #ffffff;  
    text-align: center;
    padding: 20px 0;
}

See this for reference @REYESJOHNRUIZ . 
https://docs.google.com/presentation/d/1iCoz17mBxZtIQ9PifAW0jjKsuv4xDTlx-TPQxdLySow/edit#slide=id.g25d18931cb7_3_0

**Comment by Tapispisan-YvesJohn** [comment]
Same issue: 
https://github.com/PUP-BSIT/ex7-digital_dynasty/blob/c9d47da24700cd6b08706e82bd71c8592a812a95/Reyes_JohnRuiz/works/InformationTechnology.html#L33

https://github.com/PUP-BSIT/ex7-digital_dynasty/blob/c9d47da24700cd6b08706e82bd71c8592a812a95/Reyes_JohnRuiz/works/InformationTechnology.html#L21

https://github.com/PUP-BSIT/ex7-digital_dynasty/blob/c9d47da24700cd6b08706e82bd71c8592a812a95/Reyes_JohnRuiz/works/Business.html#L27

https://github.com/PUP-BSIT/ex7-digital_dynasty/blob/c9d47da24700cd6b08706e82bd71c8592a812a95/Reyes_JohnRuiz/Reyes_JohnRuiz.html#L47

**Comment by REYESJOHNRUIZ** [comment]
Thank you!

**Comment by bergado-shamma** [comment]
Thank you po 💙
