### ISSUE TITLE
Morcoso's HTML file Issues

### ISSUE THREAD

**Issue by Cainday-Bradley** [PUP-BSIT/ex7-digital_dynasty#11]
https://github.com/PUP-BSIT/ex7-digital_dynasty/blob/c9d47da24700cd6b08706e82bd71c8592a812a95/Morcoso_Daisy/morcoso-daisy.html#L10
• Use kebab case in naming class. All lower case separated by hyphen. For example: class=”save-button”

Please see this guideline for reference: https://docs.google.com/presentation/d/1iCoz17mBxZtIQ9PifAW0jjKsuv4xDTlx-TPQxdLySow/edit#slide=id.g24da8de92d7_0_5

**Comment by Cainday-Bradley** [comment]
https://github.com/PUP-BSIT/ex7-digital_dynasty/blob/c9d47da24700cd6b08706e82bd71c8592a812a95/Morcoso_Daisy/morcoso-daisy.html#L35C30-L36C40

• Do not use the (<)br(>) element. Apply proper styling instead. (ignore the parenthesis that I use, can't type the exact element)

Please see this guideline for reference: https://docs.google.com/presentation/d/1iCoz17mBxZtIQ9PifAW0jjKsuv4xDTlx-TPQxdLySow/edit#slide=id.g28d48e53e08_0_139

**Comment by Cainday-Bradley** [comment]
https://github.com/PUP-BSIT/ex7-digital_dynasty/blob/c9d47da24700cd6b08706e82bd71c8592a812a95/Morcoso_Daisy/morcoso-daisy.html#L46C5-L51C73

• Move your CSS styling into your CSS file.

Please see this guideline for reference: https://docs.google.com/presentation/d/1iCoz17mBxZtIQ9PifAW0jjKsuv4xDTlx-TPQxdLySow/edit#slide=id.g286f540102c_1_0

**Comment by Morcoso-daisy** [comment]
Thank you!!

**Comment by bergado-shamma** [comment]
Thank you po 💙
