### ISSUE TITLE
Morcoso's CSS File Issues

### ISSUE THREAD

**Issue by Cainday-Bradley** [PUP-BSIT/ex7-digital_dynasty#12]
https://github.com/PUP-BSIT/ex7-digital_dynasty/blob/c9d47da24700cd6b08706e82bd71c8592a812a95/Morcoso_Daisy/style.css#L1

https://github.com/PUP-BSIT/ex7-digital_dynasty/blob/c9d47da24700cd6b08706e82bd71c8592a812a95/Morcoso_Daisy/style.css#L7

https://github.com/PUP-BSIT/ex7-digital_dynasty/blob/c9d47da24700cd6b08706e82bd71c8592a812a95/Morcoso_Daisy/style.css#L63

https://github.com/PUP-BSIT/ex7-digital_dynasty/blob/c9d47da24700cd6b08706e82bd71c8592a812a95/Morcoso_Daisy/style.css#L75

• Remove the unnecessary spacing.

Please see this reference for your guide: https://docs.google.com/presentation/d/1iCoz17mBxZtIQ9PifAW0jjKsuv4xDTlx-TPQxdLySow/edit#slide=id.g25d18931cb7_3_0

**Comment by Cainday-Bradley** [comment]
https://github.com/PUP-BSIT/ex7-digital_dynasty/blob/c9d47da24700cd6b08706e82bd71c8592a812a95/Morcoso_Daisy/style.css#L17C3-L18C2

https://github.com/PUP-BSIT/ex7-digital_dynasty/blob/c9d47da24700cd6b08706e82bd71c8592a812a95/Morcoso_Daisy/style.css#L23C3-L24C3

https://github.com/PUP-BSIT/ex7-digital_dynasty/blob/c9d47da24700cd6b08706e82bd71c8592a812a95/Morcoso_Daisy/style.css#L27C3-L28C3

https://github.com/PUP-BSIT/ex7-digital_dynasty/blob/c9d47da24700cd6b08706e82bd71c8592a812a95/Morcoso_Daisy/style.css#L41C3-L42C2

https://github.com/PUP-BSIT/ex7-digital_dynasty/blob/c9d47da24700cd6b08706e82bd71c8592a812a95/Morcoso_Daisy/style.css#L47C3-L48C2

https://github.com/PUP-BSIT/ex7-digital_dynasty/blob/c9d47da24700cd6b08706e82bd71c8592a812a95/Morcoso_Daisy/style.css#L52C3-L53C2

https://github.com/PUP-BSIT/ex7-digital_dynasty/blob/c9d47da24700cd6b08706e82bd71c8592a812a95/Morcoso_Daisy/style.css#L55C3-L56C2

https://github.com/PUP-BSIT/ex7-digital_dynasty/blob/c9d47da24700cd6b08706e82bd71c8592a812a95/Morcoso_Daisy/style.css#L59C3-L60C3

https://github.com/PUP-BSIT/ex7-digital_dynasty/blob/c9d47da24700cd6b08706e82bd71c8592a812a95/Morcoso_Daisy/style.css#L70C3-L71C3

https://github.com/PUP-BSIT/ex7-digital_dynasty/blob/c9d47da24700cd6b08706e82bd71c8592a812a95/Morcoso_Daisy/style.css#L84C3-L85C3

• Add a single space after the curly bracket.

Please see this reference for your guide : https://docs.google.com/presentation/d/1iCoz17mBxZtIQ9PifAW0jjKsuv4xDTlx-TPQxdLySow/edit#slide=id.g24acb740da7_0_35

**Comment by Cainday-Bradley** [comment]
https://github.com/PUP-BSIT/ex7-digital_dynasty/blob/c9d47da24700cd6b08706e82bd71c8592a812a95/Morcoso_Daisy/style.css#L9C2-L91C1

• Use proper indentation.
• Recommendation: Install a prettier extension. This may help you with the proper format of your HTML and CSS files.

Please see this reference for your guide: https://www.freecodecamp.org/news/how-to-use-prettier-in-visual-studio-code/

**Comment by bergado-shamma** [comment]
Thank you po 💙

**Comment by norona-marynicole** [comment]
Thank you po!
