### ISSUE TITLE
Bergado's files.

### ISSUE THREAD

**Issue by Ternal-AprilJoy** [PUP-BSIT/ex7-digital_dynasty#13]

**Comment by Ternal-AprilJoy** [comment]
Class names should be written in kebab case.

https://github.com/PUP-BSIT/ex7-digital_dynasty/blob/c9d47da24700cd6b08706e82bd71c8592a812a95/Bergado_Shamma/Bergado_Shamma.html#L12

https://docs.google.com/presentation/d/1iCoz17mBxZtIQ9PifAW0jjKsuv4xDTlx-TPQxdLySow/edit#slide=id.g24da8de92d7_0_5

@bergado-shamma

**Comment by Ternal-AprilJoy** [comment]
Do not use `<br>`. 

https://github.com/PUP-BSIT/ex7-digital_dynasty/blob/c9d47da24700cd6b08706e82bd71c8592a812a95/Bergado_Shamma/IT.html#L38

https://github.com/PUP-BSIT/ex7-digital_dynasty/blob/c9d47da24700cd6b08706e82bd71c8592a812a95/Bergado_Shamma/Lawyer.html#L97

https://github.com/PUP-BSIT/ex7-digital_dynasty/blob/c9d47da24700cd6b08706e82bd71c8592a812a95/Bergado_Shamma/Nurse.html#L30

https://github.com/PUP-BSIT/ex7-digital_dynasty/blob/c9d47da24700cd6b08706e82bd71c8592a812a95/Bergado_Shamma/Nurse.html#L37

https://github.com/PUP-BSIT/ex7-digital_dynasty/blob/c9d47da24700cd6b08706e82bd71c8592a812a95/Bergado_Shamma/Nurse.html#L82

https://github.com/PUP-BSIT/ex7-digital_dynasty/blob/c9d47da24700cd6b08706e82bd71c8592a812a95/Bergado_Shamma/Nurse.html#L85

https://github.com/PUP-BSIT/ex7-digital_dynasty/blob/c9d47da24700cd6b08706e82bd71c8592a812a95/Bergado_Shamma/Teacher.html#L27

https://github.com/PUP-BSIT/ex7-digital_dynasty/blob/c9d47da24700cd6b08706e82bd71c8592a812a95/Bergado_Shamma/Teacher.html#L35

https://github.com/PUP-BSIT/ex7-digital_dynasty/blob/c9d47da24700cd6b08706e82bd71c8592a812a95/Bergado_Shamma/Teacher.html#L62





https://docs.google.com/presentation/d/1iCoz17mBxZtIQ9PifAW0jjKsuv4xDTlx-TPQxdLySow/edit#slide=id.g28d48e53e08_0_139

**Comment by Ternal-AprilJoy** [comment]
Use only single space before using curly brace.


https://github.com/PUP-BSIT/ex7-digital_dynasty/blob/c9d47da24700cd6b08706e82bd71c8592a812a95/Bergado_Shamma/style2.css#L14-L15

It should be like this:

`.name img {`

https://docs.google.com/presentation/d/1iCoz17mBxZtIQ9PifAW0jjKsuv4xDTlx-TPQxdLySow/edit#slide=id.g24acb740da7_0_50

**Comment by Ternal-AprilJoy** [comment]
These `<<<<<<< HEAD` and `>>>>>>> 6193eb0dfb7d816938def23d9f5d907408d4cbfb` are conflict resolution markers which appears when you are trying to merge conflicts between different versions of the same file.

It seems like you forgot to merge these conflicts before you commit your changes. 

https://github.com/PUP-BSIT/ex7-digital_dynasty/blob/c9d47da24700cd6b08706e82bd71c8592a812a95/Bergado_Shamma/Bergado_Shamma.html#L95-L120


for reference: https://docs.google.com/presentation/d/1E9oTi1YJs6ib1PUPOiWVXxGmF7CoBsQwq1ZV1UvZBAA/edit#slide=id.g24c5cdf2528_0_74

**Comment by bergado-shamma** [comment]
Thank you po 💙
