### ISSUE TITLE
Line of code exceeded 80 characters

### ISSUE THREAD

**Issue by Villa-VillaDiana** [PUP-BSIT/ex7-digital_dynasty#14]
Reference: https://docs.google.com/presentation/d/1iCoz17mBxZtIQ9PifAW0jjKsuv4xDTlx-TPQxdLySow/edit#slide=id.g24da8de92d7_0_0

https://github.com/PUP-BSIT/ex7-digital_dynasty/blob/c9d47da24700cd6b08706e82bd71c8592a812a95/Reyes_PaulAngelo/Reyes_Paul-Angelo.html#L76

**Comment by Reyes-PaulAngelo** [comment]
Thank you!

**Comment by bergado-shamma** [comment]
Thank you po 💙
