### ISSUE TITLE
Code Suggestion

### ISSUE THREAD

**Issue by Villa-VillaDiana** [PUP-BSIT/ex7-digital_dynasty#15]
For improved readability and efficiency, consider writing the code in a single line, especially if the content is short. You may use the Prettier extension in Visual Studio Code to format your files.

https://github.com/PUP-BSIT/ex7-digital_dynasty/blob/c9d47da24700cd6b08706e82bd71c8592a812a95/Reyes_PaulAngelo/Reyes_Paul-Angelo.html#L6-L8
https://github.com/PUP-BSIT/ex7-digital_dynasty/blob/c9d47da24700cd6b08706e82bd71c8592a812a95/Reyes_PaulAngelo/Reyes_Paul-Angelo.html#L13C9-L15C14
https://github.com/PUP-BSIT/ex7-digital_dynasty/blob/c9d47da24700cd6b08706e82bd71c8592a812a95/Reyes_PaulAngelo/Reyes_Paul-Angelo.html#L18-L20
https://github.com/PUP-BSIT/ex7-digital_dynasty/blob/c9d47da24700cd6b08706e82bd71c8592a812a95/Reyes_PaulAngelo/Reyes_Paul-Angelo.html#L32-L34
https://github.com/PUP-BSIT/ex7-digital_dynasty/blob/c9d47da24700cd6b08706e82bd71c8592a812a95/Reyes_PaulAngelo/Reyes_Paul-Angelo.html#L56-L58
https://github.com/PUP-BSIT/ex7-digital_dynasty/blob/c9d47da24700cd6b08706e82bd71c8592a812a95/Reyes_PaulAngelo/Reyes_Paul-Angelo.html#L94-L96

**Comment by Reyes-PaulAngelo** [comment]
Thank you

**Comment by bergado-shamma** [comment]
Thank you po 💙
