### ISSUE TITLE
Naming Convention

### ISSUE THREAD

**Issue by Villa-VillaDiana** [PUP-BSIT/ex7-digital_dynasty#16]
Consider naming your ID something that describes its use, such as ‘works_title’. This will be helpful for debugging your code in the future. Additionally, I noticed that you didn’t use the h2 ID in your CSS. I believe it is unnecessary to include that in your code.

https://github.com/PUP-BSIT/ex7-digital_dynasty/blob/c9d47da24700cd6b08706e82bd71c8592a812a95/Reyes_PaulAngelo/Reyes_Paul-Angelo.html#L12
https://github.com/PUP-BSIT/ex7-digital_dynasty/blob/c9d47da24700cd6b08706e82bd71c8592a812a95/Reyes_PaulAngelo/Reyes_Paul-Angelo.html#L18
https://github.com/PUP-BSIT/ex7-digital_dynasty/blob/c9d47da24700cd6b08706e82bd71c8592a812a95/Reyes_PaulAngelo/Reyes_Paul-Angelo.html#L32
https://github.com/PUP-BSIT/ex7-digital_dynasty/blob/c9d47da24700cd6b08706e82bd71c8592a812a95/Reyes_PaulAngelo/Reyes_Paul-Angelo.html#L56
https://github.com/PUP-BSIT/ex7-digital_dynasty/blob/c9d47da24700cd6b08706e82bd71c8592a812a95/Reyes_PaulAngelo/Reyes_Paul-Angelo.html#L94

**Comment by Reyes-PaulAngelo** [comment]
Thank you!

**Comment by bergado-shamma** [comment]
Thank you po 💙
