### ISSUE TITLE
Code Formatting

### ISSUE THREAD

**Issue by Villa-VillaDiana** [PUP-BSIT/ex7-digital_dynasty#17]
Add a single space after the "{".

https://github.com/PUP-BSIT/ex7-digital_dynasty/blob/c9d47da24700cd6b08706e82bd71c8592a812a95/Reyes_PaulAngelo/works/styles.css#L10
https://github.com/PUP-BSIT/ex7-digital_dynasty/blob/c9d47da24700cd6b08706e82bd71c8592a812a95/Reyes_PaulAngelo/style.css#L8
https://github.com/PUP-BSIT/ex7-digital_dynasty/blob/c9d47da24700cd6b08706e82bd71c8592a812a95/Reyes_PaulAngelo/style.css#L14
https://github.com/PUP-BSIT/ex7-digital_dynasty/blob/c9d47da24700cd6b08706e82bd71c8592a812a95/Reyes_PaulAngelo/style.css#L26
https://github.com/PUP-BSIT/ex7-digital_dynasty/blob/c9d47da24700cd6b08706e82bd71c8592a812a95/Reyes_PaulAngelo/style.css#L45
https://github.com/PUP-BSIT/ex7-digital_dynasty/blob/c9d47da24700cd6b08706e82bd71c8592a812a95/Reyes_PaulAngelo/style.css#L51

**Comment by Villa-VillaDiana** [comment]
This is a duplicate issue.

**Comment by bergado-shamma** [comment]
Thank you po 💙
