### ISSUE TITLE
Unclosed Declaration in Code

### ISSUE THREAD

**Issue by Villa-VillaDiana** [PUP-BSIT/ex7-digital_dynasty#18]
It appears that the declaration has not been properly closed. Please ensure each declaration is closed to prevent potential issues in the future.

https://github.com/PUP-BSIT/ex7-digital_dynasty/blob/c9d47da24700cd6b08706e82bd71c8592a812a95/Reyes_PaulAngelo/works/styles.css#L11

**Comment by Reyes-PaulAngelo** [comment]
Thank you!

**Comment by bergado-shamma** [comment]
Thank you po 💙
