### ISSUE TITLE
Website Enhancements

### ISSUE THREAD

**Issue by Villa-VillaDiana** [PUP-BSIT/ex7-digital_dynasty#19]
- Consider having an overlay on your background or use a lighter background image. Some texts are hard to read.
  Reference: https://webdevetc.com/blog/how-to-add-a-gradient-overlay-to-a-background-image-using-just-css-and-html/
    @Reyes-PaulAngelo 
        ![image](https://github.com/PUP-BSIT/ex7-digital_dynasty/assets/146617812/5d7b021c-a58e-4af0-ac36-fba1e45ddeac)

- The color contrast of the background and text is very low. Please consider changing the color. You can use this site to check if the color contrast is good.
  WebAim Contrast Checker: https://webaim.org/resources/contrastchecker/
  Coolors Color Contrast Checker: https://coolors.co/contrast-checker/112a46-acc8e5
     @Morcoso-daisy 
        ![image](https://github.com/PUP-BSIT/ex7-digital_dynasty/assets/146617812/5422bb75-d1ed-419b-b1a2-b4eea93b023c)

- Some texts are hard to read when the background changes to a lighter color
    @REYESJOHNRUIZ 
        ![image](https://github.com/PUP-BSIT/ex7-digital_dynasty/assets/146617812/3a5ea8cf-4679-4795-92cc-3f3ad038a8bc)

- You can set a fixed height for each image so that they will look more uniform.
    @Reyes-PaulAngelo
        ![image](https://github.com/PUP-BSIT/ex7-digital_dynasty/assets/146617812/0c00bf03-c195-4640-a961-d6500e276012)
    @bergado-shamma 
        ![image](https://github.com/PUP-BSIT/ex7-digital_dynasty/assets/146617812/93fe3844-b541-4d5d-a929-86e06ab29a70)
  Reference: https://www.w3schools.com/css/css3_images.asp

**Comment by REYESJOHNRUIZ** [comment]
Thank you!

**Comment by bergado-shamma** [comment]
Thank you po 💙
