### ISSUE TITLE
Proper ID name

### ISSUE THREAD

**Issue by MentokAlmera** [PUP-BSIT/ex7-digital_dynasty#2]
https://github.com/PUP-BSIT/ex7-digital_dynasty/blob/c9d47da24700cd6b08706e82bd71c8592a812a95/norona_marynicole/act.html#L9

IDs should be written all lower case 
https://docs.google.com/presentation/d/1iCoz17mBxZtIQ9PifAW0jjKsuv4xDTlx-TPQxdLySow/edit#slide=id.g24da8de92d7_0_5

**Comment by norona-marynicole** [comment]
Thank you po!

**Comment by bergado-shamma** [comment]
Thank you po 💙
