### ISSUE TITLE
Closing tag

### ISSUE THREAD

**Issue by MentokAlmera** [PUP-BSIT/ex7-digital_dynasty#3]
No closing tag for paragraph 
https://github.com/PUP-BSIT/ex7-digital_dynasty/blob/c9d47da24700cd6b08706e82bd71c8592a812a95/norona_marynicole/act.html#L54

**Comment by norona-marynicole** [comment]
Thank you po!

**Comment by bergado-shamma** [comment]
Thank you po 💙
