### ISSUE TITLE
Proper indention

### ISSUE THREAD

**Issue by MentokAlmera** [PUP-BSIT/ex7-digital_dynasty#4]
https://docs.google.com/presentation/d/1iCoz17mBxZtIQ9PifAW0jjKsuv4xDTlx-TPQxdLySow/edit#slide=id.g29e6ce31160_0_5

https://github.com/PUP-BSIT/ex7-digital_dynasty/blob/c9d47da24700cd6b08706e82bd71c8592a812a95/norona_marynicole/act.html#L7C1-L116C18

**Comment by norona-marynicole** [comment]
Thank you po!

**Comment by bergado-shamma** [comment]
Thank you po 💙
