### ISSUE TITLE
Add a single space

### ISSUE THREAD

**Issue by MentokAlmera** [PUP-BSIT/ex7-digital_dynasty#5]
https://docs.google.com/presentation/d/1iCoz17mBxZtIQ9PifAW0jjKsuv4xDTlx-TPQxdLySow/edit#slide=id.g24acb740da7_0_35

https://github.com/PUP-BSIT/ex7-digital_dynasty/blob/c9d47da24700cd6b08706e82bd71c8592a812a95/norona_marynicole/style.css#L1

**Comment by Villa-VillaDiana** [comment]
Same issue with @Reyes-PaulAngelo. Add a single space after the "{".

https://github.com/PUP-BSIT/ex7-digital_dynasty/blob/c9d47da24700cd6b08706e82bd71c8592a812a95/Reyes_PaulAngelo/works/styles.css#L10
https://github.com/PUP-BSIT/ex7-digital_dynasty/blob/c9d47da24700cd6b08706e82bd71c8592a812a95/Reyes_PaulAngelo/style.css#L8
https://github.com/PUP-BSIT/ex7-digital_dynasty/blob/c9d47da24700cd6b08706e82bd71c8592a812a95/Reyes_PaulAngelo/style.css#L14
https://github.com/PUP-BSIT/ex7-digital_dynasty/blob/c9d47da24700cd6b08706e82bd71c8592a812a95/Reyes_PaulAngelo/style.css#L26
https://github.com/PUP-BSIT/ex7-digital_dynasty/blob/c9d47da24700cd6b08706e82bd71c8592a812a95/Reyes_PaulAngelo/style.css#L45
https://github.com/PUP-BSIT/ex7-digital_dynasty/blob/c9d47da24700cd6b08706e82bd71c8592a812a95/Reyes_PaulAngelo/style.css#L51

**Comment by norona-marynicole** [comment]
Thank you po!

**Comment by bergado-shamma** [comment]
Thank you po 💙
