### ISSUE TITLE
Class Naming Issue

### ISSUE THREAD

**Issue by Tapispisan-YvesJohn** [PUP-BSIT/ex7-digital_dynasty#7]
https://github.com/PUP-BSIT/ex7-digital_dynasty/blob/c9d47da24700cd6b08706e82bd71c8592a812a95/Reyes_JohnRuiz/Reyes_JohnRuiz.html#L75

For @REYESJOHNRUIZ, use kebab-case when adding a class in a div in html. Use this as reference:
https://docs.google.com/presentation/d/1iCoz17mBxZtIQ9PifAW0jjKsuv4xDTlx-TPQxdLySow/edit#slide=id.g24da8de92d7_0_5

**Comment by REYESJOHNRUIZ** [comment]
Thank you!

**Comment by bergado-shamma** [comment]
Thank you po 💙
