### ISSUE TITLE
Using of <br> element 

### ISSUE THREAD

**Issue by Tapispisan-YvesJohn** [PUP-BSIT/ex7-digital_dynasty#8]
https://github.com/PUP-BSIT/ex7-digital_dynasty/blob/c9d47da24700cd6b08706e82bd71c8592a812a95/Reyes_JohnRuiz/Reyes_JohnRuiz.html#L40

https://github.com/PUP-BSIT/ex7-digital_dynasty/blob/c9d47da24700cd6b08706e82bd71c8592a812a95/Reyes_JohnRuiz/Reyes_JohnRuiz.html#L41

https://github.com/PUP-BSIT/ex7-digital_dynasty/blob/c9d47da24700cd6b08706e82bd71c8592a812a95/Reyes_JohnRuiz/Reyes_JohnRuiz.html#L51

https://github.com/PUP-BSIT/ex7-digital_dynasty/blob/c9d47da24700cd6b08706e82bd71c8592a812a95/Reyes_JohnRuiz/Reyes_JohnRuiz.html#L52

https://github.com/PUP-BSIT/ex7-digital_dynasty/blob/c9d47da24700cd6b08706e82bd71c8592a812a95/Reyes_JohnRuiz/Reyes_JohnRuiz.html#L59

https://github.com/PUP-BSIT/ex7-digital_dynasty/blob/c9d47da24700cd6b08706e82bd71c8592a812a95/Reyes_JohnRuiz/Reyes_JohnRuiz.html#L60

https://github.com/PUP-BSIT/ex7-digital_dynasty/blob/c9d47da24700cd6b08706e82bd71c8592a812a95/Reyes_JohnRuiz/Reyes_JohnRuiz.html#L66

https://github.com/PUP-BSIT/ex7-digital_dynasty/blob/c9d47da24700cd6b08706e82bd71c8592a812a95/Reyes_JohnRuiz/Reyes_JohnRuiz.html#L67

Instead of using <br>, use proper styling instead, @REYESJOHNRUIZ.

**Comment by REYESJOHNRUIZ** [comment]
thank you!

**Comment by bergado-shamma** [comment]
Thank you po 💙
