### ISSUE TITLE
Inline Styling

### ISSUE THREAD

**Issue by Tapispisan-YvesJohn** [PUP-BSIT/ex7-digital_dynasty#9]
https://github.com/PUP-BSIT/ex7-digital_dynasty/blob/c9d47da24700cd6b08706e82bd71c8592a812a95/Reyes_JohnRuiz/Reyes_JohnRuiz.html#L75C1-L83C11

Always use external styling when styling a HTML file, @REYESJOHNRUIZ.

**Comment by REYESJOHNRUIZ** [comment]
Thank you!

**Comment by bergado-shamma** [comment]
Thank you po 💙
